id: AA647CE7E
title: CV_Verse 50
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:13:37.757527
  last_modified_at: 2022-03-01 23:13:37.757530
