id: AA647CE7E
title: CI_Verse 7
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:13:37.711134
  last_modified_at: 2022-03-01 23:13:37.711137
