id: AA647CE7E
title: CIII_Verse 22
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:13:37.653782
  last_modified_at: 2022-03-01 23:13:37.653786
