id: AA647CE7E
title: CIV_Verse 37
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:13:37.694611
  last_modified_at: 2022-03-01 23:13:37.694614
