id: AA647CE7E
title: CIV_Verse 40
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:13:37.699044
  last_modified_at: 2022-03-01 23:13:37.699048
